=== iolalla/jcrontab/trunk/etc/crontab.dtd
<?xml version = "1.0" encoding="iso-8859-1"?>
<!ELEMENT crontab (crontabentry)*>
<!ELEMENT crontabentry (seconds, minutes, hours, daysofmonth, months, daysofweek, bussinesdays, class, method, parameters, (startdate, enddate, years, description)?)>
<!ELEMENT seconds (#PCDATA)>
<!ELEMENT minutes (#PCDATA)>
<!ELEMENT hours (#PCDATA)>
<!ELEMENT daysofmonth (#PCDATA)>
<!ELEMENT months (#PCDATA)>
<!ELEMENT daysofweek (#PCDATA)>
<!ELEMENT bussinesdays (true|false)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT method (#PCDATA)>
<!ELEMENT parameters (#PCDATA)>
<!ELEMENT startdate (#PCDATA)>
<!ELEMENT enddate (#PCDATA)>
<!ELEMENT years (c)>
<!ELEMENT description (#PCDATA)>
<!ATTLIST crontabentry id ID #REQUIRED>
<!ATTLIST startdate format CDATA #IMPLIED>
<!ATTLIST enddate format CDATA #IMPLIED>

=== iolalla/jcrontab/etc/crontab.xml
<?xml version="1.0"?>
<!DOCTYPE crontab SYSTEM "crontab.dtd">
<crontab>
<crontabentry id="0">
	<seconds>0</seconds> 
	<minutes>*</minutes> 
	<hours>*</hours> 
	<daysofmonth>*</daysofmonth> 
	<months>*</months> 
	<daysofweek>*</daysofweek> 
	<years>*</years> 
	<bussinesdays>true</bussinesdays> 
	<startDate>null</startDate> 
	<endDate>null</endDate> 
	<class>org.jcrontab.tests.Test4</class> 
	<method>test32</method> 
	<description>null</description> 
</crontabentry>
<crontabentry id="1">
	<seconds>0</seconds> 
	<minutes>*</minutes> 
	<hours>*</hours> 
	<daysofmonth>*</daysofmonth> 
	<months>*</months> 
	<daysofweek>*</daysofweek> 
	<years>*</years> 
	<bussinesdays>true</bussinesdays> 
	<startDate>null</startDate> 
	<endDate>null</endDate> 
	<class>org.jcrontab.tests.Test4</class> 
	<method>test31 1</method> 
	<description>null</description> 
</crontabentry>
<crontabentry id="2">
	<seconds>0</seconds> 
	<minutes>*</minutes> 
	<hours>*</hours> 
	<daysofmonth>*</daysofmonth> 
	<months>*</months> 
	<daysofweek>*</daysofweek> 
	<years>*</years> 
	<bussinesdays>true</bussinesdays> 
	<startDate>null</startDate> 
	<endDate>null</endDate> 
	<class>org.jcrontab.tests.Test4</class> 
	<method>test3</method> 
	<description>null</description> 
</crontabentry>
</crontab>

=== iolalla/jcrontab/jcrontab/etc/crontab.xml
<?xml version="1.0"?>
<!DOCTYPE crontab SYSTEM "crontab.dtd">
<crontab>
<crontabentry id="0">
	<seconds>0</seconds>
	<minutes>*/3</minutes>
	<hours>3,5,6</hours>
	<daysofmonth>23</daysofmonth>
	<months>*</months>
	<daysofweek>1-5</daysofweek>
    <years>*</years>
    <bussinesdays>true</bussinesdays>
	<startdate>12/12/02</startdate>
	<enddate>19/12/02</enddate>
	<class>com.newknow.NK_Server</class>
	<method>main</method>
	<parameters>start number one</parameters>
</crontabentry>
<crontabentry id="1">
	<seconds>0</seconds>
	<minutes>*/3</minutes>
	<hours>3,5,6</hours>
	<daysofmonth>23</daysofmonth>
	<months>*</months>
	<daysofweek>1-5</daysofweek>
    	<years>*</years>
    	<bussinesdays>true</bussinesdays>
	<startdate format="dd/MM/yyyy">12/12/2002</startdate>
	<enddate format="dd/MM/yyyy">19/12/2002</enddate>
	<class>com.newknow.NK_Server4</class>
	<parameters>start number two</parameters>
    	<description>The task to run </description>
</crontabentry>
</crontab>

=== iolalla/jcrontab/trunk/jcrontab/etc/crontab.xml
<?xml version="1.0"?>
<!DOCTYPE crontab SYSTEM "crontab.dtd">
<crontab>
<crontabentry id="-1">
	<seconds>0</seconds> 
	<minutes>*</minutes> 
	<hours>*</hours> 
	<daysofmonth>*</daysofmonth> 
	<months>*</months> 
	<daysofweek>*</daysofweek> 
	<years>*</years> 
	<bussinesdays>true</bussinesdays> 
	<startDate>null</startDate> 
	<endDate>null</endDate> 
	<class>tests.test</class> 
	<method></method> 
	<parameters>1 2 3</parameters>
	<description>null</description> 
</crontabentry>
<crontabentry id="-1">
	<seconds>0</seconds> 
	<minutes>*</minutes> 
	<hours>*</hours> 
	<daysofmonth>*</daysofmonth> 
	<months>*</months> 
	<daysofweek>*</daysofweek> 
	<years>*</years> 
	<bussinesdays>true</bussinesdays> 
	<startDate>null</startDate> 
	<endDate>null</endDate> 
	<class>tests.test</class> 
	<method></method> 
	<parameters>1 2 3</parameters>
	<description>null</description> 
</crontabentry>
<crontabentry id="-1">
	<seconds>0</seconds> 
	<minutes>*</minutes> 
	<hours>*</hours> 
	<daysofmonth>*</daysofmonth> 
	<months>*</months> 
	<daysofweek>*</daysofweek> 
	<years>*</years> 
	<bussinesdays>true</bussinesdays> 
	<startDate>null</startDate> 
	<endDate>null</endDate> 
	<class>tests.test</class> 
	<method></method> 
	<parameters>1 2 3</parameters>
	<description>null</description> 
</crontabentry>
<crontabentry id="-1">
	<seconds>0</seconds> 
	<minutes>*</minutes> 
	<hours>*</hours> 
	<daysofmonth>*</daysofmonth> 
	<months>*</months> 
	<daysofweek>*</daysofweek> 
	<years>*</years> 
	<bussinesdays>true</bussinesdays> 
	<startDate>null</startDate> 
	<endDate>null</endDate> 
	<class>tests.test</class> 
	<method></method> 
	<parameters>1 2 3</parameters>
	<description>null</description> 
</crontabentry>
<crontabentry id="-1">
	<seconds>0</seconds> 
	<minutes>*</minutes> 
	<hours>*</hours> 
	<daysofmonth>*</daysofmonth> 
	<months>*</months> 
	<daysofweek>*</daysofweek> 
	<years>*</years> 
	<bussinesdays>true</bussinesdays> 
	<startDate>null</startDate> 
	<endDate>null</endDate> 
	<class>tests.test</class> 
	<method></method> 
	<parameters>1 2 3</parameters>
	<description>null</description> 
</crontabentry>
</crontab>
